SELECT NOW() - INTERVAL '1 YEAR';
/* 
 SELECT NOW() - INTERVAL '10 YEARS';
 SELECT NOW() - INTERVAL '1 MONTH';
 SELECT NOW() - INTERVAL '10 MONTHS';
 SELECT NOW() - INTERVAL '1 DAY';
 SELECT NOW() - INTERVAL '10 DAYS';
 
 SELECT NOW() + INTERVAL '1 YEAR';
 SELECT NOW() + INTERVAL '10 YEARS';
 SELECT NOW() + INTERVAL '1 MONTH';
 SELECT NOW() + INTERVAL '10 MONTHS';
 SELECT NOW() + INTERVAL '1 DAY';
 SELECT NOW() + INTERVAL '10 DAYS';
 */